#!/bin/bash

# A bash script to run RNA-Bloom.
#
# This script is intended to be placed in the same directory as the JAR file.

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [ -z ${JVM_OPTS} ]
then
    JVM_OPTS=''
fi

set -u

if [ $# -eq 0 ]
then
java ${JVM_OPTS} -jar ${DIR}/rnabloom.jar --help
else
java ${JVM_OPTS} -jar ${DIR}/rnabloom.jar "$@"
fi
