#!/bin/bash

# A bash script to run RNA-Bloom.
#
# This script is intended to be placed in the same directory as the JAR file.

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [ -z ${RNABLOOM_JAVA_OPTIONS} ]
then
    RNABLOOM_JAVA_OPTIONS=''
fi

set -u

if [ $# -eq 0 ]
then
java ${RNABLOOM_JAVA_OPTIONS} -jar ${DIR}/RNA-Bloom.jar --help
else
java ${RNABLOOM_JAVA_OPTIONS} -jar ${DIR}/RNA-Bloom.jar "$@"
fi
